
version: "3"

volumes:
    db:

services:
    api:
        user: ${UID:-1000}:${UID:-1000}
        build:
            context: ../..
            dockerfile: docker/dev/Dockerfile
        command: dev
        volumes:
            - ../../:/api
        ports:
            - 8000:8000

    db:
        image: library/mariadb:10.4
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USERNAME: app
            MYSQL_PASSWORD: app
            MYSQL_DATABASE: app
        volumes:
            - db:/var/lib/mysql