api_platform:
    title: 'Caste REST API'
    description: 'https://api.caste.dfnder.com'
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Dto']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
